------------------- Inserting Few support tickets into the ticket_message table

INSERT INTO ticket_messages (ticket_id, message_text, author, created_at) VALUES
    (1, 'Customer returned a laptop...', 'john.doe@retail.com', CURRENT_TIMESTAMP),
    (1, 'I checked the return policy...', 'support.agent@retail.com', CURRENT_TIMESTAMP),
    (2, 'Store #42 POS terminals...', 'store.manager@retail.com', CURRENT_TIMESTAMP),
    (2, 'We’ve contacted the network provider...', 'it.support@retail.com', CURRENT_TIMESTAMP),
    (3, 'What is the discount for ordering 500+ units?', 'alice.smith@retail.com', CURRENT_TIMESTAMP),
    (3, 'Our bulk discount is 15%...', 'support.agent@retail.com', CURRENT_TIMESTAMP),
    (3, 'Got it, thank you!', 'alice.smith@retail.com', CURRENT_TIMESTAMP);


------------------- Inserting Few tickets into the tickets table

INSERT INTO tickets (title, status, created_by, created_at, updated_at, priority) VALUES
    ('Unable to process return for defective item', 'open', 'john.doe@retail.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'high'),
    ('POS system offline at store #42', 'in_progress', 'store.manager@retail.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'critical'),
    ('Question about bulk discount policy', 'resolved', 'alice.smith@retail.com', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'low');


-----------------------------------------------------------------------------------Table creation
-- CREATE SCHEMA ai_ticket_support_sys_schema ;

-- Databricks SQL does not support CREATE TYPE or ENUM types.
-- Use STRING columns with CHECK constraints instead.

-- -- Tickets table
CREATE TABLE ai_ticket_support_sys_schema.tickets (
    -- ticket_id INT PRIMARY KEY AUTOINCREMENT,
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title STRING NOT NULL,
    status STRING DEFAULT 'open',
    created_by STRING NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    priority STRING DEFAULT 'medium'
    -- CONSTRAINT status_chk CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    -- CONSTRAINT priority_chk CHECK (priority IN ('low', 'medium', 'high', 'critical'))
    /*
    Only PRIMARY KEY and FOREIGN KEY constraints are currently supported.
    == SQL (line 11, position 5) ==
    CONSTRAINT status_chk CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    */
)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');
-- Fix approach: Since this is a CREATE TABLE statement (the table doesn't exist yet), we cannot enable the feature with ALTER TABLE. Instead, we need to specify the table property during table creation using TBLPROPERTIES


-- -- Ticket messages table
CREATE TABLE ai_ticket_support_sys_schema.ticket_messages (
    -- message_id INT PRIMARY KEY AUTOINCREMENT,
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    message_text STRING NOT NULL,
    author STRING NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id) ON DELETE CASCADE
    CONSTRAINT fk_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(ticket_id)
)
TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'supported');